name: Code Review with CodeGuru

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/github-actions

jobs:
  codeguru-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Java Project
        run: ./gradlew build -x test  # Skipping tests for faster builds

      - name: Run Amazon CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          s3_bucket: codeguru-reviewer-githubaction
          build_path: build/libs  # Upload compiled JARs for analysis

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Identify Changed Files
        id: changed-files
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | tr '\n' ' ')
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run CodeGuru Reviewer
        run: |
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No changed files detected. Skipping review."
            exit 0
          fi

          aws codeguru-reviewer create-code-review \
            --name "GitHub-CodeGuru-Review-${{ github.event.number }}" \
            --repository-association-arn "arn:aws:codeguru-reviewer:us-east-1:980921748291:association:29ca1ab3-f9a5-4b8d-89f7-943f17b02700" \
            --type '{"RepositoryAnalysis": {"RepositoryHead": {}}}' \
            --client-request-token "${{ github.event.pull_request.id }}"